server.port=8080

spring.application.name=classe3
spring.datasource.url=jdbc:mysql://database-1.cpcmwyu2i0d6.sa-east-1.rds.amazonaws.com:3306/curso?useSSL=false&serverTimezone=UTC
spring.datasource.username=admin
spring.datasource.password=A1b2c3d4
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

aws.region=sa-east-1
aws.accessKeyId=AKIAVD262URZVENGYRKN
aws.secretKey=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
aws.dynamo.tabela.logs=academia-java-aws
aws.sns.topic-arn=arn:aws:sns:sa-east-1:351849325683:aula-aws-topic